### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by fkjogu** [mangecoeur/preview-inline#10]
[Enter steps to reproduce below:]

1. Type `$$1 + \alpha$$` in markdown document.
2. Select only `1 + \alpha` inside.
3. Toggle the *clear* function from `Ctrl`+`Shift`+`p` selector menu.

**Atom Version**: 1.0.11
**System**: Debian GNU/Linux
**Thrown From**: [preview-inline](https://github.com/mangecoeur/preview-inline) package, v0.4.4

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /localscratch/.atom/packages/preview-inline/lib/preview-inline.coffee:86

TypeError: undefined is not a function
  at Object.module.exports.PreviewInline.clearPreviews (/localscratch/.atom/packages/preview-inline/lib/preview-inline.coffee:86:17)
  at atom-text-editor.subscriptions.add.atom.commands.add.preview-inline:clear (/localscratch/.atom/packages/preview-inline/lib/preview-inline.coffee:50:37)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -0:22.9.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:22.7.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -0:22.4.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:19.6.0 preview-inline:show (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  5x -0:17.1.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:16.1.0 vim-mode:activate-characterwise-visual-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  8x -0:15.9.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:13.7.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:12.5.0 preview-inline:show (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:11.8.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
  2x -0:11.6.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:08.8.0 command-palette:toggle (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
 17x -0:07.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:01.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.5.0 preview-inline:clear (atom-text-editor.editor.vim-mode.normal-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "rust-api-docs-helper",
      "symbols-view"
    ],
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "projectHome": "~/Development",
    "autoHideMenuBar": true
  },
  "preview-inline": {}
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.2.0
build, v0.45.0
clipboard-plus, v0.5.1
column-select, v0.2.0
highlight-line, v0.11.0
imdone-atom, v1.1.37
language-julia, v0.4.1
language-latex, v0.6.1
language-pfm, v0.81.0
language-rust, v0.4.4
latex, v0.25.1
latexer, v0.2.4
linter, v1.5.0
linter-chktex, v1.0.0
linter-rust, v0.2.9
minimap, v4.13.2
minimap-git-diff, v4.1.8
nuclide-file-watcher, v0.0.30
preview-inline, v0.4.4
racer, v0.17.1
symbol-gen, v1.0.0
theme-switcher, v1.1.0
vim-mode, v0.59.0
vim-mode-clipboard-plus, v0.1.0
vim-surround, v0.8.0

# Dev
No dev packages
```

**Comment by mangecoeur** [comment]
I haven't been able to reproduce this yet, but will throw in some extra guards in any case. If you can test after i do and see if you get the same problem that would be handy.

**Comment by fkjogu** [comment]
Sure, no problem. Just ping me.

**Comment by mangecoeur** [comment]
Found the problem should be fixed in latest version
