### ISSUE TITLE
Uncaught Error: Regex match failed

### ISSUE THREAD

**Issue by saward** [mangecoeur/preview-inline#13]
[Enter steps to reproduce below:]

Try ctrl-alt-p on the following equation:

\begin{itemize}
	\item $O_1 = \{P_1 = \{1\}, P_2 = \{2\}\}$
	\item $O_2 = \{P_3 = \{5\}, P_4 = \{9\}\}$
\end{itemize}

**Atom Version**: 1.6.2
**System**: linux 4.4.5-1-ARCH
**Thrown From**: [preview-inline](https://github.com/mangecoeur/preview-inline) package, v1.0.4

### Stack Trace

Uncaught Error: Regex match failed

```
At /home/user/.atom/packages/preview-inline/lib/preview-inline.coffee:323

Error: Regex match failed
    at Object.module.exports.PreviewInline.getMathInline (/home/user/.atom/packages/preview-inline/lib/preview-inline.coffee:323:17)
    at Object.module.exports.PreviewInline.getMathAroundCursor (/home/user/.atom/packages/preview-inline/lib/preview-inline.coffee:363:15)
    at Object.module.exports.PreviewInline.showPreview (/home/user/.atom/packages/preview-inline/lib/preview-inline.coffee:135:19)
    at atom-text-editor.subscriptions.add.atom.commands.add.preview-inline:show (/home/user/.atom/packages/preview-inline/lib/preview-inline.coffee:61:36)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -2:06.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:05.7.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -2:05.4.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -1:59.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:55.2.0 preview-inline:show (atom-text-editor.editor.is-focused)
  2x -1:49.4.0 core:cut (atom-text-editor.editor.is-focused)
     -1:48.4.0 core:save (atom-text-editor.editor.is-focused)
     -1:28 application:open-file (atom-text-editor.editor.is-focused)
     -0:48.6.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:46.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:46.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:45.1.0 application:open-file (atom-text-editor.editor.is-focused)
  2x -0:23.3.0 preview-inline:show (atom-text-editor.editor.is-focused)
     -0:08.6.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:08.6.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:00.8.0 preview-inline:show (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "latextools"
    ]
  },
  "preview-inline": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.1
autocomplete-go, v1.0.5
builder-go, v1.0.0
environment, v1.2.0
file-icons, v1.7.1
go-config, v1.1.4
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.4
gometalinter-linter, v1.1.0
gorename, v1.0.1
imdone-atom, v1.3.29
language-latex, v0.6.1
latex, v0.32.0
latexer, v0.3.0
linter, v1.11.4
navigator-godef, v1.0.2
pdf-view, v0.50.0
pigments, v0.26.0
preview-inline, v1.0.4
project-manager, v2.9.4
tester-go, v1.0.3

# Dev
No dev packages
```

**Comment by mangecoeur** [comment]
I will look into this - I mostly test on markdown so Latex still has glitches.

**Comment by mangecoeur** [comment]
You should now be able to preview the `$O_2 = {P_3 = {5}, P_4 = {9}}$` segments individually, but not the whole `itemize` block because that's not marked as a math block by the LaTeX grammar

**Comment by mangecoeur** [comment]
This should now be fixed- I believe I have removed all conditions which could throw a regex error. If the text you select cannot be processed at all you should just get a small 'nothing to preview' warning.
